### ISSUE TITLE
Architecture ARM cannot be checked

### ISSUE THREAD

**Issue by DrKrapfen** [aaronparker/packagefactory#24]
I created my own Zoom ARM app package using the information on evergreen. Invoke Evergreen with $_.Architecture set to ARM64 works but not via the packagefactory.
![image](https://github.com/aaronparker/packagefactory/assets/38590398/92b7cc38-f4cc-43eb-bd2f-9b16e7a50414)

**Comment by aaronparker** [comment]
The `-Architecture` parameter on the `New-IntuneWin32AppRequirementRule` function only supports `All`, `x86`, and `x64`. 

You might have to open a feature request at https://github.com/MSEndpointMgr/IntuneWin32App to support ARM64; however, you could also solve this issue with a PowerShell script requirement rule that checks for ARM64.
