### ISSUE TITLE
PostInstall: Copy function anomaly

### ISSUE THREAD

**Issue by skyblaster** [aaronparker/packagefactory#29]
With the build script below, initial_preferences.txt does land in C:\Users\Jason\Downloads\GoogleChrome\Source\
```powershell
Set-Location -Path "C:\projects\packagefactory"
$params = @{
    Path        = "C:\projects\packagefactory\packages"
    Application = "GoogleChrome"
    Type        = "App"
    WorkingPath = "C:\Users\Jason\Downloads"
    Import      = $true
}
.\New-Win32Package.ps1 @params
```

However, I'm seeing the following error on client machines using the stock Chrome example:
`<![LOG[Copy-File: Cannot find destination: C:\Program Files\Google\Chrome\Application\initial_preferences]LOG]!>`

**Comment by aaronparker** [comment]
This should be working now - see PR #34. I've tested this with Chrome in my lab and I'm not getting the expected `initial_preferences` file
